version: '3.8'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - PRODUCT_SERVICE_URL=http://product-service:8081
      - ORDER_SERVICE_URL=http://order-service:8082
      - CUSTOMER_SERVICE_URL=http://customer-service:8083

  product-service:
    build: ./product-service
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=mongodb://mongo:27017/products

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=mongodb://mongo:27017/orders

  customer-service:
    build: ./customer-service
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=mongodb://mongo:27017/customers

  mongo:
    image: mongo
    ports:
      - "27017:27017"